name: 'Airbrake Sourcemap Action'
description: 'Syncs up Airbrake sourcemaps with a JS build manifest file.'
inputs:
  airbrake-id:
    description: 'Airbrake ID - required for Airbrake authentication'
    required: true
  airbrake-key:
    description: 'Airbrake Key - required for Airbrake authentication'
    required: true
  build-path:
    description: 'Build path - This is the build path where the manifest assets are located.'
    required: true
  manifest:
    description: 'JSON Manifest - this is a JSON object representing the manifest file'
    required: true

outputs:
  log: # id of output
    description: 'A log of what happened during this action run.'
runs:
  using: 'node12'
  main: 'index.js'
